- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      change_when: False
  
  tasks:
    - include: tasks/packages.yml
    - include: tasks/dotfiles.yml
    - include: tasks/user.yml
    - include: tasks/cron.yml
    - include: tasks/wallpaper-set.yml
