 - name: copy wallpaper file
   copy:
     src: file/wallpaper.png
     dest: /usr/share/backgrounds/ansible-wallpaper.png
     owner: root
     group: root
 
 - name: set wallpaper
   dconf:
     key: "/org/gnome/desktop/background/picture-uri"
     value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"
 
 - name: set wallpaper posititon
   dconf:
     key: "/org/gnome/desktop/background/picture-uri"
     value: "'zoom'"